version: "3"
services:
  mysql_database:
    container_name: mysql_database
    hostname: mysql_database
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root # root password
      MYSQL_DATABASE: school # database
      #MYSQL_USER: root # database user
      MYSQL_PASSWORD: root # database user password
